server:
  port: 8088

spring:
  datasource: # 数据源的相关配置
    url: jdbc:mysql://192.168.2.112:3306/foodie-shop-prod?useUnicode=true&characterEncoding=UTF-8&autoReconnect
  redis:
    database: 1
    host: localhost
    port: 6379
    password: