server:
  port: 8088

spring:
  datasource: # 数据源的相关配置
    url: jdbc:mysql://192.168.2.112:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect
    password: ok
  redis:
    database: 0
    host: 192.168.2.112
    port: 6379
    password: ok
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #sql语句在控制台打印
